### ISSUE TITLE
Does not support PE files using extensions other than EXE or DLL

### ISSUE THREAD

**Issue by RichardTea** [symstore/symstore#20]
symstore currently does a naiive file extension check and rejects all files with extensions other than PDB, EXE and DLL.

However, many standard Windows PE binaries use extensions other than EXE or DLL, eg:
- acm : Windows audio codec library (internally a DLL)
- ax : DirectShow video codec library (DLL)
- ocx : ActiveX plugin (DLL)
- scr : Screensaver (EXE)
- sys : Driver (DLL)

Additionally, the majority of applications that have a plugin architecture use a custom extension for their plugins, even though they are 'normal' Windows DLLs.
For example, Vectorworks Windows binary plugins use the extension "vlb"

symstore rejects all of these due to the initial file extension check.

Instead it should initially assume anything that is not "pdb" or "pd_" is a PE file.
It will then raise a PEFormatError if the file is not in fact a Windows PE file.

**Comment by elmjag** [comment]
Yeah, it should probably just check if signature/magic number that corresponds to PDB or PE file format is present. I'll look into this...

**Comment by elmjag** [comment]
I changed the code to 'probe' file types instead:

https://github.com/symstore/symstore/commit/355b815f9c7c3f7036df782de40826bf724d6f42

I.e. it does not care about file name extensions at all. Should work to publish *.acm, *.ax, *.sys, et all files now.
