### ISSUE TITLE
Committing large numbers of files is very slow when compression is enabled

### ISSUE THREAD

**Issue by RichardTea** [symstore/symstore#24]
makecab.exe and GCab are both single-threaded, so on a modern machine the CPU load stays very low.

This commit step in symstore.py should be done in parallel if compression is enabled:
```
        # publish all entries files to the store
        for entry in self.entries:
            entry.publish()
```

**Comment by elmjag** [comment]
fixed in v0.3.4 (https://github.com/symstore/symstore/commit/7514bc18e60749d5f7575b265b9a9a0bc372c7b1)

Thanks RichardTea!
