### ISSUE TITLE
Creates wrong path

### ISSUE THREAD

**Issue by t-b** [symstore/symstore#25]
```
$ pip show symstore
Name: symstore
Version: 0.3.3
Summary: publish PDB and PE files to symbols store
Home-page: https://github.com/symstore/symstore
Author:
Author-email:
License: MIT
Location: c:\users\thomas\anaconda3\lib\site-packages
Requires:
Required-by:
```

I added the following file, only zipped for github,
[itcXOP2-64.zip](https://github.com/symstore/symstore/files/9716088/itcXOP2-64.zip) to our symbolserver with symstore.

Now I can't access it with Visual Studio/CDB. The reason seems to be that the generated path is different in symstore (python) vs symstore (microsoft).

```
symstore.exe test itcXOP2-64.xop
```

```
$ ls -lR test
test:
total 0
drwxr-xr-x 1 thomas 197121 0 Oct  5 15:41 000Admin/
drwxr-xr-x 1 thomas 197121 0 Oct  5 15:41 itcXOP2-64.xop/
-rw-r--r-- 1 thomas 197121 0 Oct  5 15:41 pingme.txt

test/000Admin:
total 4
-rw-r--r-- 1 thomas 197121 51 Oct  5 15:41 0000000001
-rw-r--r-- 1 thomas 197121 49 Oct  5 15:41 history.txt
-rw-r--r-- 1 thomas 197121 10 Oct  5 15:41 lastid.txt
-rw-r--r-- 1 thomas 197121 51 Oct  5 15:41 server.txt

test/itcXOP2-64.xop:
total 0
drwxr-xr-x 1 thomas 197121 0 Oct  5 15:41 5AA043B37D000/

test/itcXOP2-64.xop/5AA043B37D000:
total 476
-rwxr-xr-x 1 thomas 197121 485376 Oct  5 15:41 itcXOP2-64.xop*
```

```
E:\test-ms>"c:\Program Files (x86)/Windows Kits/10/Debuggers/x64/symstore.exe" add /s . /l /f e:\itcXOP2-64.xop /o /t test
```

```
$ ls -lR test-ms/
test-ms/:
total 0
drwxr-xr-x 1 thomas 197121 0 Oct  5 15:41 000Admin/
drwxr-xr-x 1 thomas 197121 0 Oct  5 15:41 itcXOP2-64.xop/
-rw-r--r-- 1 thomas 197121 0 Oct  5 15:41 pingme.txt

test-ms/000Admin:
total 4
-rw-r--r-- 1 thomas 197121 52 Oct  5 15:41 0000000001
-rw-r--r-- 1 thomas 197121 53 Oct  5 15:41 history.txt
-rw-r--r-- 1 thomas 197121 10 Oct  5 15:41 lastid.txt
-rw-r--r-- 1 thomas 197121 55 Oct  5 15:41 server.txt

test-ms/itcXOP2-64.xop:
total 0
drwxr-xr-x 1 thomas 197121 0 Oct  5 15:41 5AA043B37d000/

test-ms/itcXOP2-64.xop/5AA043B37d000:
total 477
-rwxr-xr-x 1 thomas 197121 485376 Apr 20 00:01 itcXOP2-64.xop*
-rw-r--r-- 1 thomas 197121     44 Oct  5 15:41 refs.ptr
```

The microsoft version generates `5AA043B37d000` whereas this program generates `5AA043B37D000`.

As URLs are case sensitive the symbol search fails.

**Comment by elmjag** [comment]
There is a fix here now: https://github.com/symstore/symstore/commit/dcab9b4f648678278e002b80461bc50bf08b80a7

Some post-mortem notes. The reason that this issue have not been noticed previously, is because the part of the hash that is supposed to be in lower cases, is based on PE files 'size of image'. If 'size of image' in hex only contains 0-9 numbers, that there is no difference between lower or upper cases.

I'm planning to include this fix into the next release.

**Comment by t-b** [comment]
Thanks for the fix. Is there an ETA for a release?

**Comment by elmjag** [comment]
Unfortunately, I don't know an exact ETA, but I hope I can sit down someday this week and do a release.

**Comment by t-b** [comment]
Very nice!

**Comment by RichardTea** [comment]
I've just hit this as well, when do you expect to be able to do a release?

Unfortunately I didn't notice until _after_ we'd created a few hundred items with the wrong path :(
