### ISSUE TITLE
Question: Compressed files with http symbol store

### ISSUE THREAD

**Issue by t-b** [symstore/symstore#30]
[I'm happy to move this question to a better fitting place, I just could not find one]

I'm currently using symstore with compression (`-z`). And just tried to retrieve one of the compressed pdb files using symchk.exe. And the problem I have is that symchk.exe is not even trying to download the `pd_` file:

```
SYMSRV:  HTTPGET: //index2.txt
SYMSRV:  HttpQueryInfo: 801901f4 - HTTP_STATUS_SERVER_ERROR
SYMSRV:  HTTPGET: /ITCXOP2-64.pdb/8DB6890FB625415E8723A03EDD0596751/ITCXOP2-64.pdb
SYMSRV:  HttpQueryInfo: 801901f4 - HTTP_STATUS_SERVER_ERROR
SYMSRV:  RESULT: 0x801901F4
```

So now I'm wondering if someone else is using symstore with compression and is serving the symbols via http?

**Comment by elmjag** [comment]
Regarding a better fitting place. Let's try using 'Discussions' tab for this project.

Try making a new discussion topic here: https://github.com/symstore/symstore/discussions/new/choose

**Comment by t-b** [comment]
@elmjag Thanks. Done -> https://github.com/symstore/symstore/discussions/31.
