### ISSUE TITLE
Compression is  not available when installed into a virtual environment

### ISSUE THREAD

**Issue by t-b** [symstore/symstore#34]
I've switched now to install symstore into a venv. As one is supposed to do.

Unfortunately the compression does now not work anymore.

I get:

```
(.venv) ci@c4573fb16029:~$ ~/.venv/bin/symstore -z a
gcab module not available, compression not supported
```

where as when I install it globally I get

```
(.venv) ci@c4573fb16029:~$ ~/.local/bin/symstore -z a
no new files to publish
```

**Comment by elmjag** [comment]
For compression to work inside the venv environment you need enable access to `system site packages`.

If you create your venv environment with `--system-site-packages` flag, the compression will work. For example:

    $ python3 -m venv --system-site-packages  .venv
    $ source .venv/bin/activate
    (.venv) $ pip install symstore
    Collecting symstore
      Using cached symstore-0.3.4-py2.py3-none-any.whl (16 kB)
    Installing collected packages: symstore
    Successfully installed symstore-0.3.4
    (.venv) $ symstore -z a
    no new files to publish

I guess I should add the above tidbit into the README file.

**Comment by t-b** [comment]
@elmjag Thanks for the explanation. Passing `--system-site-packages` did the trick.

**Comment by elmjag** [comment]
added information on how to make compression work inside virtual environment in the [README](https://github.com/symstore/symstore?tab=readme-ov-file#virtual-environments) file.
