### ISSUE TITLE
Add support for refs.ptr file generation

### ISSUE THREAD

**Issue by bretdavi89** [symstore/symstore#35]
I noticed that symstore does not generate the refs.ptr file that is used for tracking transaction history for files that are identical between builds, as documented here: https://learn.microsoft.com/en-us/windows/win32/debug/using-symstore#symbol-storage-format

Is there some existing mechanism in this tool that tracks this information in a different way? Basically, concerned that if a transaction is deleted, will it delete files that were part of that transaction that existed before via an earlier transaction

**Comment by elmjag** [comment]
The tools does check if files are referenced from multiple transactions before deleting them. It does that by reading the symstore meta-data from the 000Admin directory.

For example file `<hash>/foo.pdb` is referenced both in transactions `0000000001` and `0000000002`. When you delete transaction `0000000001`, the `<hash>/foo.pdb` will not be deleted. You need to delete both transaction before the file will be deleted.

Here is that code that calculates which files are removed when transaction is deleted:
https://github.com/symstore/symstore/blob/master/symstore/symstore.py#L396

I don't really see the need of generating refs.ptr files.
