### ISSUE TITLE
Inconsistent Formatting for PE Hash

### ISSUE THREAD

**Issue by bretdavi89** [symstore/symstore#36]
Here is pertinent line: https://github.com/symstore/symstore/blob/10200d54c725e08b35186d2ee3a5bf8e3b42613c/symstore/symstore.py#L54

In our symbol store noticed difference in directory hash from the windows symstore tool, and what's generated by this implementation.

Official tool has padded hex value for PE file timestamp in hash, whereas it isn't padded here, e.g.:
```
>>> '%X' % pe_file.TimeDateStamp
'4A30CF0'
>>> '%.8X' % pe_file.TimeDateStamp
'04A30CF0'
```

So this:
`"%X%x" % (pefile.TimeDateStamp, pefile.SizeOfImage)`
should be:
`"%.8X%x" % (pefile.TimeDateStamp, pefile.SizeOfImage)`

**Comment by bretdavi89** [comment]
Any feedback?

**Comment by elmjag** [comment]
Sorry, I've been super busy! I'll try to take a look during next weekend.

**Comment by elmjag** [comment]
Hah, yes, the padding was not done correctly. So if you need to publish a PE file from the 1970s, it would not work correctly :)

I have pushed a fix, thanks for the bug report!
